### ISSUE TITLE
Is it possible to test with private local EOS platform?

### ISSUE THREAD

**Issue by djKooks** [memtrip/eosreach#2]
I'm trying to develop android app connecting with EOS, so referring this app. Thanks for your work.
Is there a way to make this application connect with local EOS chain?

**Comment by samkirton** [comment]
yeah if you switch to the `dev` build variant you can point to a chain running on local host. The repository currently assumes that you are running `nodeos` on port 8888. You can change the port and ip address from this config file though:
https://github.com/memtrip/eosreach/blob/master/android/app/src/dev/res/values/config_strings.xml
